sudo: false
language: python
os:
  - linux
python:
  - 2.7
  - pypy
matrix:
  fast_finish: true
  allow_failures:
    - python: pypy

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  - pip
  - directories:
    - $HOME/.cache/pip

before_install:
  - pip install --upgrade pip setuptools wheel coveralls codacy-coverage

install:
  - python setup.py install

script:
  - python setup.py test --pytest-args '-vv --full-trace --cov=wscheck --benchmark-skip'

after_success:
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml
